### PR TITLE
eu-legal additions

### PR DESCRIPTION
**Pull request by jBangiev**

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @jBangiev,

For this module, I guess we do not need to copy paste the whole content of `hookPayment()`.
But we still need to call it, at least to assign the properly values to smarty.

I also suggest to move a common test in another new function: hasAllowedCurrencies().

Here is my version:

``` php
    public function hasAllowedCurrencies()
    {
        $allowedCurrencies = $this->getCurrency((int)$params['cart']->id_currency);
        foreach ($allowedCurrencies AS $allowedCurrency)
            if ($allowedCurrency['id_currency'] == $params['cart']->id_currency)
                return true;

        return false;
    }

    public function hookDisplayPaymentEU($params) {
        global $smarty, $cookie;

        if (hasAllowedCurrencies()) {
            $this->hookPayment($params);

            $localMethods = Configuration::get('MB_LOCAL_METHODS');
            $interMethods = Configuration::get('MB_INTER_METHODS');

            $result = array();

            $metods = array(
                'inter' => $interMethods ? explode('|', $interMethods) : array(),
                'local' => $localMethods ? explode('|', $localMethods) : array()
            );

            foreach ($metods as $k => $method_list) {
                $logos = ${$k . '_logos'};

                foreach ($method_list as $index => $method) {
                    $smarty->assign('code', $logos[$method]['code']);

                    array_push($result, array(
                        'cta_text' => $this->l('Pay using') . ' ' . $logos[$method]['name'],
                        'logo' => Media::getMediaPath(dirname(__FILE__) . '/logos/' . ($k == 'local' ? $k : 'international') . '/' . $logos[$method]['file'] . '.gif'),
                        'form' => $smarty->fetch(dirname(__FILE__) . '/moneybookers_eu.tpl')
                    ));
                }
            }

            return sizeof($result) ? $result : false;
        }

        return false;
    }
```

**Comment by jBangiev** [comment]
updated

**Comment by Quetzacoalt91** [comment]
Hi @jBangiev,

Be careful, you made more changes on your side and a few variables are not defined anymore !
In example: local, inter, display_mode.

**Comment by jBangiev** [comment]
Hi, I've fixed it.

**Comment by Quetzacoalt91** [comment]
Hi @jBangiev,

Thanks, your PR has just been merged.

Regards

**Pull request merged**
